-- 문제 테이블 생성
CREATE TABLE `TESTS` (
	`TESTS_ID`	VARCHAR(50)	NOT NULL,
	`QUESTIONS`	VARCHAR(255)	NULL,
	`POINT`	DECIMAL(20,0)	NULL,
	`QUESTION_NUM`	DECIMAL(20,0)	NULL
);

-- 사용자 테이블 생성
CREATE TABLE `USER` (
	`USER_ID`	VARCHAR(50)	NOT NULL,
	`USER`	VARCHAR(100)	NULL
);

-- 응답 테이블 생성
CREATE TABLE `RESPOND` (
	`RESPOND_ID`	VARCHAR(50)	NOT NULL,
	`TESTS_ID`	VARCHAR(50)	NOT NULL,
	`USER_ID`	VARCHAR(50)	NOT NULL,
	`OPTION_ID`	VARCHAR(50)	NOT NULL
);

-- 보기 문항 테이블 생성
CREATE TABLE `OPTION` (
	`OPTION_ID`	VARCHAR(50)	NOT NULL,
	`TESTS_ID`	VARCHAR(50)	NOT NULL,
	`OPTION`	VARCHAR(255)	NULL,
	`CORRECT`	VARCHAR(10)	NULL,
	`OPTION_NUM`	VARCHAR(10)	NULL
);

-- 시험 문제 테이블의 PRIMARY_KEY 속성 지정
ALTER TABLE `TESTS` ADD CONSTRAINT `PK_TESTS` PRIMARY KEY (
	`TESTS_ID`
);

-- 사용자 테이블의 PRIMARY_KEY 속성 지정
ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`USER_ID`
);

-- 사용자 응답 테이블의 PRIMARY_KEY 및 FOREIGN_KEY 속성 지정
ALTER TABLE `RESPOND` ADD CONSTRAINT `PK_RESPOND` PRIMARY KEY (
	`RESPOND_ID`,
	`TESTS_ID`,
	`USER_ID`,
	`OPTION_ID`
);

-- 보기 문항의 테이블의 PRIMARY_KEY 및 FOREIGN_KEY 속성 지정
ALTER TABLE `OPTION` ADD CONSTRAINT `PK_OPTION` PRIMARY KEY (
	`OPTION_ID`,
	`TESTS_ID`
);

-- 사용자 응답 테이블과 문제 테이블의 연결성 정의
ALTER TABLE `RESPOND` ADD CONSTRAINT `FK_TESTS_TO_RESPOND_1` FOREIGN KEY (
	`TESTS_ID`
)
REFERENCES `TESTS` (
	`TESTS_ID`
);

-- 사용자 응답 테이블과 사용자 테이블의 연결성 정의
ALTER TABLE `RESPOND` ADD CONSTRAINT `FK_USER_TO_RESPOND_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER` (
	`USER_ID`
);

-- 사용자 응답 테이블과 보기 문항 테이블의 연결성 정의
ALTER TABLE `RESPOND` ADD CONSTRAINT `FK_OPTION_TO_RESPOND_1` FOREIGN KEY (
	`OPTION_ID`
)
REFERENCES `OPTION` (
	`OPTION_ID`
);

-- 보기 문항 테이블과 문제 테이블의 연결성 정의
ALTER TABLE `OPTION` ADD CONSTRAINT `FK_TESTS_TO_OPTION_1` FOREIGN KEY (
	`TESTS_ID`
)
REFERENCES `TESTS` (
	`TESTS_ID`
);

