-- 사용자가 응답 테이블에 문제 테이블과 보기 테이블 중 정답 여부 컬럼에 값이 채워진 라인을 기준으로 이너 조인을 해서 
-- 사용자가 입력한 값이 정답인 것들을 매칭한 뒤 사용자 별 문제 당 점수를 갖고 온다.
SELECT  RESPOND.USER_ID,RESPOND.OPTION_ID, OPTION_CORRECT.CORRECT, TESTS.`POINT`
FROM RESPOND
INNER JOIN (
			SELECT *
			FROM `OPTION`
			WHERE CORRECT IS NOT NULL
) AS OPTION_CORRECT
ON OPTION_CORRECT.OPTION_ID = RESPOND.OPTION_ID
INNER JOIN TESTS ON TESTS.TESTS_ID = RESPOND.TESTS_ID
;

-- 위 조인한 내용을 그대로 사용자 정보 테이블에 이너 조인해서
-- USER_ID 기준으로 사용자의 순서를 정렬한 뒤
-- 정렬된 사용자 이름 별 맞춘 점수의 합계(총점)을 가져온다.
SELECT `USER`.`USER`,`USER`.USER_ID, SUM(CORRECT_ANSWER.`POINT`)
FROM `USER`
INNER JOIN (
	SELECT RESPOND.USER_ID,RESPOND.OPTION_ID, OPTION_CORRECT.CORRECT, TESTS.`POINT`
	FROM RESPOND
	INNER JOIN (
				SELECT *
				FROM `OPTION`
				WHERE CORRECT IS NOT NULL
	) AS OPTION_CORRECT
	ON OPTION_CORRECT.OPTION_ID = RESPOND.OPTION_ID
	INNER JOIN TESTS ON TESTS.TESTS_ID = RESPOND.TESTS_ID) AS CORRECT_ANSWER ON CORRECT_ANSWER.USER_ID = `USER`.USER_ID
GROUP BY USER_ID
ORDER BY USER_ID, CAST(SUBSTRING_INDEX(`USER`.USER_ID, '_', -1) AS UNSIGNED);
