SELECT `USER`.`USER`,`USER`.USER_ID, SUM(CORRECT_ANSWER.POINT)
FROM `USER`
INNER JOIN (
	SELECT RESPOND.USER_ID,RESPOND.OPTION_ID, OPTION_CORRECT.CORRECT, TESTS.`POINT`
	FROM RESPOND
	INNER JOIN (
				SELECT *
				FROM `OPTION`
				WHERE CORRECT IS NOT NULL
	) AS OPTION_CORRECT
	ON OPTION_CORRECT.OPTION_ID = RESPOND.OPTION_ID
	INNER JOIN TESTS ON TESTS.TESTS_ID = RESPOND.TESTS_ID) AS CORRECT_ANSWER 
    ON CORRECT_ANSWER.USER_ID = `USER`.USER_ID
GROUP BY USER_ID
ORDER BY USER_ID, CAST(SUBSTRING_INDEX(`USER`.USER_ID, '_', -1) AS UNSIGNED);

SELECT USER.USER, USER.USER_ID, SUM(CORRECT_ANSWER.POINT)
FROM USER
INNER JOIN (
    SELECT RESPOND.USER_ID, RESPOND.OPTION_ID, OPTION_CORRECT.CORRECT, TESTS.POINT
    FROM RESPOND
    INNER JOIN (
        SELECT *
        FROM `OPTION`
        WHERE CORRECT IS NOT NULL
    ) AS OPTION_CORRECT
    ON OPTION_CORRECT.OPTION_ID = RESPOND.OPTION_ID
    INNER JOIN TESTS ON TESTS.TESTS_ID = RESPOND.TESTS_ID
) AS CORRECT_ANSWER 
ON CORRECT_ANSWER.USER_ID = USER.USER_ID
GROUP BY USER_ID
ORDER BY USER_ID, CAST(SUBSTRING_INDEX(USER.USER_ID, '_', -1) AS UNSIGNED);